# Generated by Django 5.1.5 on 2025-04-04 03:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0004_recruiterprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vacante',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Tiempo completo'), ('part_time', 'Medio tiempo'), ('contract', 'Contrato'), ('temporary', 'Temporal'), ('internship', 'Prácticas')], default='full_time', max_length=20, verbose_name='Tipo de empleo'),
        ),
        migrations.AddField(
            model_name='vacante',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='company',
            field=models.CharField(default='Empresa no especificada', max_length=100, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='description',
            field=models.TextField(default='Sin descripción', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='location',
            field=models.CharField(default='Ubicación no especificada', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='requirements',
            field=models.TextField(default='Sin requisitos especificados', verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='salary',
            field=models.CharField(default='Salario no especificado', max_length=100, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='title',
            field=models.CharField(default='Sin título', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
