# Generated by Django 5.1.5 on 2025-04-04 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0007_remove_profile_image_profile_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente por confirmar'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacantes.vacante')),
            ],
            options={
                'unique_together': {('usuario', 'vacante')},
            },
        ),
        migrations.AddField(
            model_name='vacante',
            name='postulantes',
            field=models.ManyToManyField(related_name='vacantes_postuladas', through='vacantes.Postulacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
