# Generated by Django 5.1.5 on 2025-04-04 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0008_postulacion_vacante_postulantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='vacantes_favoritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='salary',
            field=models.CharField(blank=True, default='Salario no especificado', max_length=100, null=True, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='vacante',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
    ]
